### ISSUE TITLE
Issue with main queue

### ISSUE THREAD

**Issue by gitIkerKristian** [SSamanta/SSQRScanner#1]
According to official documentation you should provide new serial queue to `<AVCaptureMetadataOutput>`, also don't forget to dispatch back to main, once the data is retrieved.

**Comment by SSamanta** [comment]
@gitIkerKristian Can you please let me know more details of issue? Sorry for late reply

**Comment by gitIkerKristian** [comment]
You should set new queue to `<AVCaptureMetadataOutput>`object, instead of main queue as you did. This won't freeze UI.

**Comment by gitIkerKristian** [comment]
Something like:
```
let captureMetadataOutput = AVCaptureMetadataOutput()
captureMetadataOutput.setMetadataObjectsDelegate(self, queue: DispatchQueue(label: "my_new_queue"))
```

**Comment by SSamanta** [comment]
Fixed above one with latest swift 4 code update
